from api import SessionLocal, Complaint, User, Officer, DepartmentPolicy, SLAConfiguration, EscalationConfiguration, EscalationHistory, Notification
db = SessionLocal()
db.query(Complaint).delete()
db.query(User).delete()
db.query(Officer).delete()
db.query(DepartmentPolicy).delete()
db.query(SLAConfiguration).delete()
db.query(EscalationConfiguration).delete()
db.query(EscalationHistory).delete()
db.query(Notification).delete()
db.commit()
print("Database forcibly wiped so it can re-seed with correct L1 assignments on startup!")
